### ISSUE TITLE
Option to specify file name for esbuild-plugin-html output

### ISSUE THREAD

**Issue by ChildishGiant** [chialab/rna#15]
Currently it's not possible for me to use my dev script for esbuild with this as each time a change is made I'll need to open up a new page since the hash changed. An option to omit the hash would solve this.

**Comment by Thiht** [comment]
Agree, I'm not sure the hash in the generated HTML file is necessary anyway.
The HTML plugin works great, but the hash in the HTML filename makes it harder to serve.

**Comment by edoardocavazza** [comment]
Hello @ChildishGiant and @Thiht, thanks for the feedback! I have published the 0.7.0 version that should respect esbuild configuration for `assetNames`, `chunkNames` and `entryNames`. Let me know if this fix the issue.

**Comment by nerdfoundrygaming** [comment]
Hi there, I'm brand new to esbuild but loving it so far, and running into this issue with trying to figure out the best practice for this... Since the entrypoint *is* the html file, it's weird that it's treated as an asset, and thus hashed as the rest. Because of this, if I set `assetNames` to just `[name]` then ALL assets are not hashed, which means cache-busting isn't as easy.

With my build config modified with:
```
  ...,
  entryPoints: ['./src/index.html'],
  assetNames: 'ASSETNAME[name]',
  entryNames: 'ENTRYNAME[name]',
  chunkNames: 'CHUNKNAME[name]',
  ...
```

I get the following build output:

```
./dist/
./dist/CHUNKNAME2.js.map
./dist/ASSETNAMEfavicon-16x16.png
./dist/ASSETNAMEfavicon-32x32.png
./dist/ASSETNAMEnavConnect.png
./dist/ASSETNAMEapple-touch-icon.png
./dist/ASSETNAMEfavicon-196x196.png
./dist/CHUNKNAME2.js
./dist/css
./dist/css/CHUNKNAME1.css
./dist/css/CHUNKNAME1.css.map
./dist/ASSETNAMEapple-touch-icon-ipad.png
./dist/ASSETNAMEnavSub.png
./dist/ASSETNAMEfavicon-48x48.png
./dist/ASSETNAMElogo.png
./dist/ASSETNAMEindex.html
````

Notice how my `index.html` is prefixed with `ASSETNAME`, where I'd fully expect it to say `ENTRYNAME`, allowing me to properly target `index.html` to serve, and still have hashed assets for images, css, and js.

Am I misunderstanding this, or is this a bug?

**Comment by nerdfoundrygaming** [comment]
Just saw `0.15.3` release and this commit https://github.com/chialab/rna/commit/e7c73d4a29ff7a8a705b5193750644a40a962ae0

Looks pretty much like what I was doing 😅

One caveat/input I'd say is the auto-gen bundle that you create I think should be treated as an asset, and NOT and entry.

But otherwise, thanks for the update!
