### ISSUE TITLE
esbuild-plugin-commonjs not transform commonjs to esm

### ISSUE THREAD

**Issue by ruanyl** [chialab/rna#31]
I was trying to convert react to ESM so that browser can consume it as a native ESM module. 

Tested with esbuild-plugin-commonjs@0.12.31

Here is esbuild setup:
```
import { build } from "esbuild";
import commonjsPlugin from "@chialab/esbuild-plugin-commonjs";

await build({
  entryPoints: [
    "./node_modules/react/index.js",
  ],
  bundle: true,
  outfile: "out.js",
  format: "esm",
  loader: {
    ".js": "js",
  },
  plugins: [commonjsPlugin()],
})
```

The output is still commonjs module style while I was expecting `module.exports` to be converted to ESM `export` statements

**Comment by edoardocavazza** [comment]
Hello @ruanyl!

I don't think you need the commonjs plugin for your use case since you are using the `bundle: true` option without externals.

Esbuild itself should bundle commonjs dependencies and export React as default specifier. In fact, at the end of the out.js file I can see the statement:

```js
export default require_react();
```

Do you have a different output?

**Comment by ruanyl** [comment]
@edoardocavazza Thanks for your reply :) I probably had some misunderstandings of the use-case of commonjs plugin.

Yes, I have React exported as default, but the problem with esbuild `forma: 'esm'` is it didn't create `export` for named exports, such as `useCallback, useMemo`, etc.

What I'm trying to do is compile React to native ESM so that I can use it directly in the browser without bundling it.

**Comment by edoardocavazza** [comment]
You understood it correctly, but there ~are~ were two problems here.

The first one ~is~ was a bug 😅 I should have addressed it with the 0.12.39 version. Thank you for reporting!

The second one is a "design" choice: the commonjs plugin *can* transform `module.exports.something` to `export const something`, the problem here is that the React entrypoint exposes the whole module to `module.exports`.
AFAIK, even Node loads this kind of modules using default specifier, so I intended the plugin this way.

BUT, you can try to change the entrypoint to `"./node_modules/react/cjs/react.development.js"`, which correctly assigns named references to the `module.exports`.

**Comment by edoardocavazza** [comment]
Hi @ruanyl , have you managed to create an ESM-based React package? Can we close this issue?

**Comment by ruanyl** [comment]
@edoardocavazza Yep, thanks for the help, closing now :)
